pipeline {

    agent none

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            agent any
            steps {
                git branch: 'main',
                    url: 'https://github.com/Deepak-kandukuri/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Build') {
            agent any
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            agent any
            steps {
                sh 'java -jar target/hello-world-1.0.jar'
            }
        }
    }

    post {
        success {
            echo 'Pipeline Executed Successfully'
        }
        failure {
            echo 'Pipeline Failed'
        }
    }
}
