pipeline {

    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    environment {
        IMAGE_NAME = "hello-world"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Deepak-kandukuri/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Build') {
            steps {
                dir('Deepakk') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Run Application') {
            steps {
                dir('Deepakk') {
                    sh 'java -jar target/hello-world-1.0.jar'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Deepakk') {
                    sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker rm -f hello-container || true

                docker run -d \
                  --name hello-container \
                  ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }

        stage('Verify Container') {
            steps {
                sh 'docker ps -a'
                sh 'docker logs hello-container'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }

        failure {
            echo 'Pipeline failed'
        }
    }
}
