pipeline {

    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/Deepak-kandukuri/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Build') {
            steps {
                dir('Deepak') {
                    sh 'pwd'
                    sh 'ls -lrt'
                    sh 'mvn clean package'
                }
            }
        }

        stage('Run Application') {
            steps {
                dir('Deepak') {
                    sh 'java -jar target/hello-world-1.0.jar'
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully'
        }

        failure {
            echo 'Pipeline failed'
        }
    }
}
